# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='something string', max_length=1000),
        ),
    ]
