# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0003_auto_20180815_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book',
            new_name='books',
        ),
    ]
